---
- hosts: 172.31.41.253
  become: yes
  tasks:
  - name: i want to run direct linux commands
    command: sudo apt-get install apache2
    register: myresult

  - name: i want to display my first task result
    debug:
      msg: "{{myresult}}"

  - name: install git
    apt:
      name: git
      state: present 
    when: myresult.stderr != ""

  - name: install wget
    apt:
      name: wget
      state: present  
    when: myresult.stderr == ""   