---
- hosts: 172.31.41.253
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present 

  - name: install wget
    apt:
      name: wget
      staate: present 

  - name: install tree
    apt:
      name: tree
      state: present  